import Head from "next/head";
import { Hero } from "@/components/hero/hero";
import { Navigation } from "@/components/navigation/navigation";
import { Footer } from "@/components/footer/footer";
import { AboutUs } from "@/components/about-us/about-us";
import { Services } from "@/components/services/services";
import { ScheduleAnAppointment } from "@/components/schedule-an-appointment/schedule-an-appointment";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <Hero />
        <Services />
        <ScheduleAnAppointment />
        <AboutUs />
        <Footer />
      </main>
    </>
  );
}
